server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postGIS
    password: mahtab238
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
